# Generated by Django 5.2.7 on 2025-10-23 10:38

import candidates.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de soumission"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de révision"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Raison du rejet (si applicable)",
                        verbose_name="Raison du rejet",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "candidate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Candidat",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="categories.category",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_candidatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Révisé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-submitted_at"],
                "unique_together": {("candidate", "category")},
            },
        ),
        migrations.CreateModel(
            name="CandidatureFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Vidéo"),
                            ("portfolio", "Portfolio"),
                            ("audio", "Audio"),
                        ],
                        max_length=20,
                        verbose_name="Type de fichier",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=candidates.models.candidature_file_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "mp3",
                                    "wav",
                                ]
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Titre descriptif du fichier (optionnel)",
                        max_length=200,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage des fichiers",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="candidates.candidature",
                        verbose_name="Candidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier de candidature",
                "verbose_name_plural": "Fichiers de candidature",
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
