# Generated by Django 5.2.7 on 2025-10-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaturefile',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('portfolio', 'Portfolio'), ('audio', 'Audio'), ('documents', 'Documents')], max_length=20, verbose_name='Type de fichier'),
        ),
    ]
