# Generated by Django 5.2.7 on 2025-10-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidaturefile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaturefile',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('portfolio', 'Portfolio'), ('audio', 'Audio')], max_length=20, verbose_name='Type de fichier'),
        ),
    ]
