# Generated by Django 5.2.7 on 2025-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la candidature par le candidat', verbose_name='Description'),
        ),
    ]
