# Generated by Django 5.2.7 on 2025-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidature_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='published',
            field=models.BooleanField(default=False, help_text='La candidature est-elle publiée et visible au public ?', verbose_name='Publiée'),
        ),
    ]
