# Generated by Django 5.2.7 on 2025-10-31 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], verbose_name='Année')),
                ('category_name', models.CharField(max_length=200, verbose_name='Catégorie/Prix')),
                ('winner_name', models.CharField(max_length=200, verbose_name='Nom du lauréat')),
                ('winner_photo', models.ImageField(blank=True, null=True, upload_to='hall_of_fame/', verbose_name='Photo du lauréat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('award_type', models.CharField(blank=True, help_text='Ex: 1er Prix, Meilleur Performance, etc.', max_length=100, verbose_name='Type de récompense')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hall of Fame',
                'verbose_name_plural': 'Hall of Fame',
                'ordering': ['-year', 'order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='HeroCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_carousel/', verbose_name='Image')),
                ('title', models.CharField(blank=True, help_text="Titre optionnel pour l'image", max_length=200, verbose_name='Titre')),
                ('alt_text', models.CharField(blank=True, help_text="Description de l'image pour l'accessibilité", max_length=200, verbose_name='Texte alternatif')),
                ('order', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image du carousel Hero',
                'verbose_name_plural': 'Images du carousel Hero',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countdown_enabled', models.BooleanField(default=True, verbose_name='Activer le chronomètre')),
                ('countdown_target_date', models.DateTimeField(blank=True, help_text='Date à laquelle le chronomètre se terminera', null=True, verbose_name='Date cible du chronomètre')),
                ('hero_carousel_enabled', models.BooleanField(default=True, verbose_name='Activer le carousel')),
                ('hero_carousel_auto_play', models.BooleanField(default=True, verbose_name='Lecture automatique')),
                ('hero_carousel_interval', models.IntegerField(default=5000, help_text='Temps entre chaque transition (1000-30000 ms)', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)], verbose_name='Intervalle entre les slides (ms)')),
                ('site_title', models.CharField(default='Makona Awards 2025', max_length=200, verbose_name='Titre du site')),
                ('site_description', models.TextField(blank=True, help_text='Meta description pour le SEO', verbose_name='Description du site')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL Twitter/X')),
                ('youtube_url', models.URLField(blank=True, verbose_name='URL YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_members/', verbose_name='Photo')),
                ('role', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-Président'), ('secretary', 'Secrétaire'), ('treasurer', 'Trésorier'), ('member', 'Membre'), ('advisor', 'Conseiller')], default='member', max_length=50, verbose_name='Rôle')),
                ('member_type', models.CharField(choices=[('active_bureau', 'Bureau Actif'), ('member', 'Membre')], default='member', max_length=20, verbose_name='Type de membre')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = plus haut)", verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL Facebook')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL Twitter/X')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['member_type', 'order', 'last_name', 'first_name'],
            },
        ),
    ]
