# Generated by Django 5.2.7 on 2025-10-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Nom de l'icône Lucide (ex: Music, Dance, etc.)",
                        max_length=50,
                        verbose_name="Icône Lucide",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                (
                    "color_gradient",
                    models.CharField(
                        help_text="Classes Tailwind CSS (ex: from-purple-500 to-pink-500)",
                        max_length=50,
                        verbose_name="Dégradé de couleur",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Catégorie active"),
                ),
                (
                    "requires_photo",
                    models.BooleanField(default=True, verbose_name="Photo obligatoire"),
                ),
                (
                    "requires_video",
                    models.BooleanField(
                        default=False, verbose_name="Vidéo obligatoire"
                    ),
                ),
                (
                    "requires_portfolio",
                    models.BooleanField(
                        default=False, verbose_name="Portfolio obligatoire"
                    ),
                ),
                (
                    "requires_audio",
                    models.BooleanField(
                        default=False, verbose_name="Audio obligatoire"
                    ),
                ),
                (
                    "max_video_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Durée maximale autorisée pour les vidéos (en secondes)",
                        null=True,
                        verbose_name="Durée max vidéo (secondes)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
            },
        ),
    ]
