# Generated by Django 5.2.7 on 2025-10-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='requires_documents',
            field=models.BooleanField(default=False, verbose_name='Documents obligatoires'),
        ),
    ]
