# Generated by Django 5.2.7 on 2025-10-25 02:26

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_requires_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_audio_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée maximale autorisée pour les audios (en secondes)', null=True, validators=[categories.models.validate_audio_duration], verbose_name='Durée max audio (secondes)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée maximale autorisée pour les vidéos (en secondes)', null=True, validators=[categories.models.validate_video_duration], verbose_name='Durée max vidéo (secondes)'),
        ),
    ]
