# Generated by Django 5.2.7 on 2025-10-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_max_audio_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la classe')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='tag', max_length=50, verbose_name='Icône')),
                ('color_gradient', models.CharField(default='from-blue-500 to-purple-600', max_length=100, verbose_name='Dégradé de couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Classe de catégorie',
                'verbose_name_plural': 'Classes de catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category_class',
            field=models.ForeignKey(blank=True, help_text='Classe à laquelle appartient cette catégorie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.categoryclass', verbose_name='Classe de catégorie'),
        ),
    ]
