# Generated by Django 5.2.7 on 2025-10-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categoryclass_category_category_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryclass',
            name='color_gradient',
        ),
        migrations.RemoveField(
            model_name='categoryclass',
            name='icon',
        ),
        migrations.AlterField(
            model_name='categoryclass',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
    ]
