# Generated by Django 5.2.7 on 2025-10-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_categoryclass_color_gradient_and_more'),
        ('categories', '0005_remove_icon_color_gradient'),
    ]

    operations = [
    ]
