# Generated by Django 5.2.7 on 2025-10-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_merge_20251027_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='awards_certificate',
            field=models.BooleanField(default=False, help_text='Cette catégorie attribue un satisfecit', verbose_name='Satisfecit'),
        ),
        migrations.AddField(
            model_name='category',
            name='awards_monetary',
            field=models.BooleanField(default=False, help_text='Cette catégorie attribue des primes monétaires', verbose_name='Primes monétaires'),
        ),
        migrations.AddField(
            model_name='category',
            name='awards_trophy',
            field=models.BooleanField(default=False, help_text='Cette catégorie attribue un trophée', verbose_name='Trophée'),
        ),
    ]
