# Generated by Django 5.2.7 on 2025-10-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_awards_certificate_category_awards_monetary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='awards_plaque',
            field=models.BooleanField(default=False, help_text='Cette catégorie attribue une plaque commémorative', verbose_name='Plaque commémorative'),
        ),
    ]
